name: Deploy to MWAA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Copy DAGs and requirements.txt to S3
        run: |
          # Copy DAGs to S3
          aws s3 cp dags/ s3://${{ vars.MWAA_BUCKET }}/dags/ --recursive
          # Copy requirements.txt to S3 bucket root
          aws s3 cp requirements.txt s3://${{ vars.MWAA_BUCKET }}/requirements.txt

      - name: Update MWAA Environment
        run: |
          aws mwaa update-environment --name ${{ vars.MWAA_ENV_NAME }}
